-- COMANDOS PARA ESCLUIR AS TABELAS (SE NECESSÁRIO)
/*
DROP TABLE T_FTC_USUARIO CASCADE CONSTRAINTS;
DROP TABLE T_FTC_CONTA CASCADE CONSTRAINTS;
DROP TABLE T_FTC_RECEITAS CASCADE CONSTRAINTS;
DROP TABLE T_FTC_DESPESAS CASCADE CONSTRAINTS;
DROP TABLE T_FTC_INVESTIMENTOS CASCADE CONSTRAINTS;
*/

-- COMANDOS PARA EXCLUIR AS LINHAS DAS TABELAS (SE NECESSÁRIO)
/*
DELETE FROM T_FTC_USUARIO;
DELETE FROM T_FTC_CONTA;
DELETE FROM T_FTC_RECEITAS;
DELETE FROM T_FTC_DESPESAS;
DELETE FROM T_FTC_INVESTIMENTOS;
*/

-- Tabela de Usuários
CREATE TABLE T_FTC_USUARIO (
    ID_USUARIO  NUMBER(4) GENERATED ALWAYS AS IDENTITY,
    NM_USUARIO  VARCHAR2(100) NOT NULL,
    EMAIL       VARCHAR2(100) NOT NULL,
    SENHA       VARCHAR2(100) NOT NULL,
    DT_CADASTRO DATE DEFAULT SYSDATE
);

-- Constraints da Tabela Usuários
   ALTER TABLE T_FTC_USUARIO
ADD CONSTRAINT PK_FTC_USUARIO
   PRIMARY KEY (ID_USUARIO);

   ALTER TABLE T_FTC_USUARIO
ADD CONSTRAINT UN_FTC_USUARIO_EMAIL
        UNIQUE (EMAIL);

-- Tabela de Contas
CREATE TABLE T_FTC_CONTA (
    ID_CONTA    NUMBER(4) GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO  NUMBER(4)    NOT NULL,
    TP_CONTA    VARCHAR2(50) NOT NULL,
    VL_SALDO    NUMBER(10,2) DEFAULT 0,
    DT_ABERTURA DATE DEFAULT SYSDATE
);

-- Constraints da Tabela Conta
   ALTER TABLE T_FTC_CONTA
ADD CONSTRAINT PK_FTC_CONTA
   PRIMARY KEY (ID_CONTA);

   ALTER TABLE T_FTC_CONTA
ADD CONSTRAINT CK_FTC_CONTA_TIPO_CONTA
         CHECK (TP_CONTA IN ('CORRENTE','POUPANÇA'));

   ALTER TABLE T_FTC_CONTA
ADD CONSTRAINT CK_FTC_CONTA_SALDO
         CHECK (VL_SALDO >= 0);

-- Tabela de Receitas
CREATE TABLE T_FTC_RECEITAS (
    ID_RECEITA NUMBER(4) GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO NUMBER(4)      NOT NULL,
    ID_CONTA   NUMBER(4)      NOT NULL,
    DS_RECEITA VARCHAR2(255)  NOT NULL,
    VL_RECEITA NUMBER(10, 2)  NOT NULL,
    DT_RECEITA DATE DEFAULT SYSDATE
);

-- Constraints da Tabela Receitas
   ALTER TABLE T_FTC_RECEITAS
ADD CONSTRAINT PK_FTC_RECEITAS
   PRIMARY KEY (ID_RECEITA);

   ALTER TABLE T_FTC_RECEITAS
ADD CONSTRAINT CK_FTC_RECE_VALOR_RECEITA
         CHECK (VL_RECEITA > 0);

-- Tabela de Despesas
CREATE TABLE T_FTC_DESPESAS (
    ID_DESPESA NUMBER(4) GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO NUMBER(4)     NOT NULL,
    ID_CONTA   NUMBER(4)     NOT NULL,
    DS_DESPESA VARCHAR2(255) NOT NULL,
    VL_DESPESA NUMBER(10, 2) NOT NULL,
    DT_DESPESA DATE DEFAULT SYSDATE
);

-- Constraints da Tabela Despesas
   ALTER TABLE T_FTC_DESPESAS
ADD CONSTRAINT PK_FTC_DESPESAS
   PRIMARY KEY (ID_DESPESA);

   ALTER TABLE T_FTC_DESPESAS
ADD CONSTRAINT CK_FTC_DESP_VALOR_DESPESA
         CHECK (VL_DESPESA > 0);

-- Tabela de Investimentos
CREATE TABLE T_FTC_INVESTIMENTOS (
    ID_INVESTIMENTO NUMBER(4) GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO      NUMBER(4)     NOT NULL,
    ID_CONTA        NUMBER(4)     NOT NULL,
    DS_INVESTIMENTO VARCHAR2(255) NOT NULL,
    VL_INVESTIMENTO NUMBER(10, 2) NOT NULL,
    DT_INVESTIMENTO DATE DEFAULT SYSDATE
);

-- Constraints da Tabela Investimentos
   ALTER TABLE T_FTC_INVESTIMENTOS
ADD CONSTRAINT PK_FTC_INVESTIMENTOS
   PRIMARY KEY (ID_INVESTIMENTO);

   ALTER TABLE T_FTC_INVESTIMENTOS
ADD CONSTRAINT CK_FTC_INVE_VALOR_INVESTIMENTO
         CHECK (VL_INVESTIMENTO > 0);

-- CONSTRAINTS CHAVES ESTRANGEIRAS (FOREIGN KEY)
   ALTER TABLE T_FTC_CONTA
ADD CONSTRAINT FK_FTC_CONTA_USUARIO
   FOREIGN KEY (ID_USUARIO)
    REFERENCES T_FTC_USUARIO (ID_USUARIO);

   ALTER TABLE T_FTC_RECEITAS
ADD CONSTRAINT FK_FTC_RECEITAS_USUARIO
   FOREIGN KEY (ID_USUARIO)
    REFERENCES T_FTC_USUARIO (ID_USUARIO);

   ALTER TABLE T_FTC_RECEITAS
ADD CONSTRAINT FK_FTC_RECEITAS_CONTA
   FOREIGN KEY (ID_CONTA)
    REFERENCES T_FTC_CONTA (ID_CONTA);

   ALTER TABLE T_FTC_DESPESAS
ADD CONSTRAINT FK_FTC_DESPESAS_USUARIO
   FOREIGN KEY (ID_USUARIO)
    REFERENCES T_FTC_USUARIO (ID_USUARIO);

   ALTER TABLE T_FTC_DESPESAS
ADD CONSTRAINT FK_FTC_DESPESAS_CONTA
   FOREIGN KEY (ID_CONTA)
    REFERENCES T_FTC_CONTA (ID_CONTA);

   ALTER TABLE T_FTC_INVESTIMENTOS
ADD CONSTRAINT FK_FTC_INVESTIMENTOS_USUARIO
   FOREIGN KEY (ID_USUARIO)
    REFERENCES T_FTC_USUARIO (ID_USUARIO);

   ALTER TABLE T_FTC_INVESTIMENTOS
ADD CONSTRAINT FK_FTC_INVESTIMENTOS_CONTA
   FOREIGN KEY (ID_CONTA)
    REFERENCES T_FTC_CONTA (ID_CONTA);

-- Cadastrar os dados do usuário
INSERT INTO T_FTC_USUARIO (NM_USUARIO, EMAIL, SENHA)
     VALUES ('[NOME DO USUÁRIO]', '[EMAIL DO USUÁRIO]', '[SENHA DO USUÁRIO]');

-- Cadastrar os dados para a conta do usuário
INSERT INTO T_FTC_CONTA (ID_USUARIO, TP_CONTA, VL_SALDO)
     VALUES ([ID DO USUÁRIO], '[TIPO DE CONTA]', [VALOR DO SALDO]);

-- Cadastrar as receitas do usuário
INSERT INTO T_FTC_RECEITAS (ID_USUARIO, DS_RECEITA, VL_RECEITA)
     VALUES ([ID DO USUÁRIO], '[DESCRIÇÃO DA RECEITA]', [VALOR DA RECEITA]);

-- Cadastrar as despesas do usuário
INSERT INTO T_FTC_DESPESAS (ID_USUARIO, DS_DESPESA, VL_DESPESA)
     VALUES ([ID DO USUÁRIO], '[DESCRIÇÃO DA DESPESA]', [VALOR DA DESPESA]);

-- Cadastrar os dados para investimentos
INSERT INTO T_FTC_INVESTIMENTOS (ID_USUARIO, DS_INVESTIMENTO, VL_INVESTIMENTO)
     VALUES ([ID DO USUÁRIO], '[DESCRIÇÃO DO INVESTIMENTO]', [VALOR DO INVESTIMENTO]);

SELECT * FROM T_FTC_USUARIO;

-- Alterar todos os dados do usuário
UPDATE T_FTC_USUARIO
   SET NM_USUARIO = '[NOVO NOME]', EMAIL = '[NOVO EMAIL]', SENHA = '[NOVA SENHA]'
 WHERE ID_USUARIO = [ID DO USUÁRIO];

-- Alterar todos os dados das receitas do usuário
UPDATE T_FTC_RECEITAS
   SET DS_RECEITA = '[NOVA DESCRIÇÃO]', VL_RECEITA = [NOVO VALOR]
 WHERE ID_RECEITA = [ID DA RECEITA];

-- Alterar todos os dados das despesas do usuário
UPDATE T_FTC_DESPESAS
   SET DS_DESPESA = '[NOVA DESCRIÇÃO]', VL_DESPESA = [NOVO VALOR]
 WHERE ID_DESPESA = [ID DA DESPESA];

-- Alterar todos os dados para investimentos do usuário
UPDATE T_FTC_INVESTIMENTOS
   SET DS_INVESTIMENTO = '[NOVA DESCRIÇÃO]', VL_INVESTIMENTO = [NOVO VALOR]
 WHERE ID_INVESTIMENTO = [ID DO INVESTIMENTO];

-- Consultar os dados de um usuário
SELECT NM_USUARIO, EMAIL, DT_CADASTRO 
  FROM T_FTC_USUARIO
 WHERE ID_USUARIO = [ID DO USUÁRIO];

-- Consultar os dados de um único registro de despesa de um usuário 
SELECT DS_DESPESA, VL_DESPESA, DT_DESPESA 
  FROM T_FTC_DESPESAS
 WHERE ID_USUARIO = [ID DO USUÁRIO] AND ID_DESPESA = [ID DA DESPESA];

-- Consultar os dados de todos os registros de despesas de um usuário, ordenando dos registros mais recentes para os mais antigos
  SELECT DS_DESPESA, VL_DESPESA, DT_DESPESA 
    FROM T_FTC_DESPESAS
   WHERE ID_USUARIO = [ID DO USUÁRIO]
ORDER BY DT_DESPESA DESC;

-- Consultar os dados de um único registro de investimento de um usuário 
SELECT DS_INVESTIMENTO, VL_INVESTIMENTO, DT_INVESTIMENTO 
  FROM T_FTC_INVESTIMENTOS
 WHERE ID_USUARIO = [ID DO USUÁRIO] AND ID_INVESTIMENTO = [ID DO INVESTIMENTO];

-- Consultar os dados de todos os registros de investimentos de um usuário, ordenando dos registros mais recentes para os mais antigos
  SELECT DS_INVESTIMENTO, VL_INVESTIMENTO, DT_INVESTIMENTO 
    FROM T_FTC_INVESTIMENTOS
   WHERE ID_USUARIO = [ID DO USUÁRIO]
ORDER BY DT_INVESTIMENTO DESC;

-- Consultar os dados básicos de um usuário, o último investimento registrado e a última despesa registrada
SELECT u.n
